import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: [
      "src/index.ts",
      "src/utils/transcribe-audio-node.ts",
      "src/plugin-discovery-node.ts",
      "src/utils/pdf-pdftotext-node.ts",
      "src/utils/pdf-plumber-node.ts",
      "src/utils/xlsx-pandas-node.ts",
      "src/utils/import-node-util.ts",
      "src/utils/resolve-exiftool-node.ts",
    ],
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: true,
    target: "es2022",
    platform: "neutral",
    external: [
      "jszip",
      "linkedom",
      "mammoth",
      "turndown",
      "xlsx",
      "magika",
      "pdfjs-dist",
      "@kenjiuno/msgreader",
      "youtube-transcript-plus",
      "@azure/identity",
      "@azure/core-auth",
      "@azure/ai-content-understanding",
      "jschardet",
      "./transcribe-audio-node.js",
      "../utils/transcribe-audio-node.js",
      "./plugin-discovery-node.js",
      "../plugin-discovery-node.js",
      "./utils/pdf-pdftotext-node.js",
      "../utils/pdf-pdftotext-node.js",
      "./utils/resolve-exiftool-node.js",
      "../utils/resolve-exiftool-node.js",
    ],
  },
  {
    entry: [
      "src/cli.ts",
      "src/utils/transcribe-audio-node.ts",
      "src/plugin-discovery-node.ts",
      "src/utils/pdf-pdftotext-node.ts",
      "src/utils/pdf-plumber-node.ts",
      "src/utils/xlsx-pandas-node.ts",
      "src/utils/import-node-util.ts",
    ],
    format: ["cjs"],
    sourcemap: true,
    target: "node18",
    platform: "node",
    outDir: "dist",
    external: [
      "jszip",
      "linkedom",
      "mammoth",
      "turndown",
      "xlsx",
      "magika",
      "pdfjs-dist",
      "@kenjiuno/msgreader",
      "youtube-transcript-plus",
      "@azure/identity",
      "@azure/core-auth",
      "@azure/ai-content-understanding",
      "jschardet",
      "./transcribe-audio-node.js",
      "../utils/transcribe-audio-node.js",
      "./plugin-discovery-node.js",
      "../plugin-discovery-node.js",
      "./utils/pdf-pdftotext-node.js",
      "../utils/pdf-pdftotext-node.js",
      "./utils/resolve-exiftool-node.js",
      "../utils/resolve-exiftool-node.js",
    ],
  },
]);
